import type { ConductorConfig, DelegationHandoff, RouteDecision } from "./types.js";

const validationHints = (): string[] => [
	"Inspect this repo's package.json, Makefile, or documentation for available script targets.",
	"Run the narrowest relevant formatter/typecheck/lint/test commands available in this repo.",
	"Report back if no suitable validation or testing setup exists.",
];

const executionProfile = (tier: NonNullable<RouteDecision["tier"]>, config: ConductorConfig): string[] => {
	const profile = config.profiles[tier];
	const descriptions: Record<NonNullable<RouteDecision["tier"]>, string> = {
		instant: "linear direct worker; exact files; no scout; compact return",
		rapid: "linear direct worker; bounded edits; optional scout if targets are unclear",
		verified: "orchestrated bounded flow; scout/context recommended; verification required",
		deep: "orchestrated deep flow; scout, plan, execute, verify, and review recommended",
	};
	const shape = profile.topology === "linear" ? "linear direct-worker profile" : "orchestrated profile";
	return [
		`${tier}: ${shape}; ${descriptions[tier]}.`,
		`Topology: ${profile.topology}; scout: ${profile.scout}; verification: ${profile.verification}; review: ${profile.review ? "yes" : "no"}; max worker visits: ${profile.maxWorkerVisits}.`,
		profile.topology === "linear"
			? "Proceed directly unless the task scope is unclear; keep reads/edits tightly task-scoped."
			: "Use parent-owned orchestration recommendations for scout/plan/execute/review handoffs; do not launch workers from this handoff.",
	];
};

export function buildDelegationHandoff(task: string, decision: RouteDecision, config: ConductorConfig): DelegationHandoff {
	const tier = decision.tier ?? "rapid";
	const allowedFiles = decision.signals.mentionedFiles.length > 0 ? decision.signals.mentionedFiles : ["<parent must confirm allowed files before launch>"];

	const prompt = [
		`Goal: ${task.trim()}`,
		"",
		`Conductor route: ${decision.route}`,
		decision.suggestedAgent ? `Suggested agent: ${decision.suggestedAgent}` : undefined,
		decision.suggestedModel ? `Preferred model: ${decision.suggestedModel}` : undefined,
		"",
		"Allowed files:",
		...allowedFiles.map((file) => `- ${file}`),
		"",
		"Parent decisions / implementation notes:",
		`- This is a ${tier} delegation handoff generated by Conductor.`,
		"- Keep the diff minimal and task-scoped.",
		"- Prefer existing project patterns over new abstractions.",
		"",
		"Execution profile:",
		...executionProfile(tier, config).map((policy) => `- ${policy}`),
		"",
		"Non-goals:",
		"- Do not redesign architecture beyond this task.",
		"- Do not touch unrelated files.",
		"- Do not commit, push, deploy, publish, reset, clean, or discard changes.",
		"",
		"Stop rules:",
		"- Stop and report if an unapproved product, API, architecture, security, persistence, or deployment decision is required.",
		"- Stop and report if the requested files/scope are insufficient.",
		"- If validation fails, make at most one focused fix attempt, then report status.",
		"",
		"Suggested validation:",
		...validationHints().map((command) => `- ${command}`),
		"",
		"Return format:",
		"Summary:",
		"Files Changed:",
		"Commands Run:",
		"Validation Result:",
		"Residual Risks:",
	].filter((line): line is string => typeof line === "string");

	return { decision, prompt: prompt.join("\n") };
}

export function formatHandoff(handoff: DelegationHandoff): string {
	return ["```text", handoff.prompt, "```"].join("\n");
}
