import type { ConductorConfig, ConductorTier, DelegationHandoff, RouteDecision } from "./types.js";

const VALIDATION_HINTS = [
	"Inspect this repo's package.json, Makefile, or documentation for available script targets.",
	"Run the narrowest relevant formatter/typecheck/lint/test commands available in this repo.",
	"Report back if no suitable validation or testing setup exists.",
] as const;

const EVIDENCE_BY_TIER: Record<ConductorTier, readonly string[]> = {
	instant: ["Changed files", "Command run, if obvious/applicable", "Compact summary"],
	fast: ["Changed files", "Tests/lint/typecheck if available", "Risk notes"],
	careful: [
		"Changed files",
		"Tests run",
		"Review findings",
		"Fixes applied",
		"E2E/manual evidence where relevant",
		"Screenshots/logs if UI-relevant",
		"Residual risks",
		"Explicit ready/not-ready verdict",
	],
};

const PROFILE_DESCRIPTIONS: Record<ConductorTier, string> = {
	instant: "linear direct worker; exact files; no scout; compact return",
	fast: "linear direct worker; bounded edits; optional scout if targets are unclear",
	careful: "full orchestrated flow; scout, plan, execute, verify, and review recommended",
};

const bullets = (lines: readonly string[]): string[] => lines.map((line) => `- ${line}`);
const section = (title: string, lines: readonly string[]): string[] => [`${title}:`, ...bullets(lines)];

const executionProfile = (tier: ConductorTier, config: ConductorConfig): string[] => {
	const profile = config.profiles[tier];
	const shape = profile.topology === "linear" ? "linear direct-worker profile" : "orchestrated profile";
	const guidance =
		profile.topology === "linear"
			? "Proceed directly unless the task scope is unclear; keep reads/edits tightly task-scoped."
			: "Use parent-owned orchestration recommendations for scout/plan/execute/review handoffs; do not launch workers from this handoff.";

	return [
		`${tier}: ${shape}; ${PROFILE_DESCRIPTIONS[tier]}.`,
		`Topology: ${profile.topology}; scout: ${profile.scout}; verification: ${profile.verification}; review: ${profile.review ? "yes" : "no"}; max worker visits: ${profile.maxWorkerVisits}.`,
		guidance,
	];
};

export function buildDelegationHandoff(task: string, decision: RouteDecision, config: ConductorConfig): DelegationHandoff {
	const tier = decision.tier ?? "fast";
	const taskText = task.trim();
	const allowedFiles = decision.signals.mentionedFiles.length > 0 ? decision.signals.mentionedFiles : ["<parent must confirm allowed files before launch>"];

	const prompt = [
		`Goal: ${taskText}`,
		"",
		`Conductor route: ${decision.route}`,
		`Route confidence: ${Math.round(decision.confidence * 100)}%`,
		decision.suggestedAgent ? `Suggested agent: ${decision.suggestedAgent}` : undefined,
		decision.suggestedModel ? `Preferred model: ${decision.suggestedModel}` : undefined,
		"",
		...section("Desired outcome", [
			`Complete the requested outcome: ${taskText}`,
			"Preserve existing behavior outside the requested scope.",
		]),
		"",
		...section("Why it matters", [
			"This handoff lets the parent chat delegate bounded implementation while retaining responsibility for scope, review, and user decisions.",
		]),
		"",
		...section("Allowed files", allowedFiles),
		"",
		...section("Constraints / implementation notes", [
			`This is a ${tier} delegation handoff generated by Conductor.`,
			"Keep the diff minimal and task-scoped.",
			"Prefer existing project patterns over new abstractions.",
		]),
		"",
		...section("Execution profile", executionProfile(tier, config)),
		"",
		...section("Non-goals", [
			"Do not redesign architecture beyond this task.",
			"Do not touch unrelated files.",
			"Do not commit, push, deploy, publish, reset, clean, or discard changes.",
		]),
		"",
		...section("Escalate to human if", [
			"An API/design choice, product behavior change, destructive migration/deletion, security/persistence/deployment decision, or broad refactor expansion is required.",
			"Validation cannot be run or the requested files/scope are insufficient.",
			"Strict mode means no scope expansion or ambiguous product/design decisions without human approval.",
		]),
		"",
		...section("Auto-fix allowed for", ["Typos, lint/type errors, missing imports, and obvious bugs against the stated goal."]),
		"",
		...section("Stop rules", [
			"Stop and report if an unapproved product, API, architecture, security, persistence, or deployment decision is required.",
			"Stop and report if the requested files/scope are insufficient.",
			"If validation fails, make at most one focused fix attempt, then report status.",
		]),
		"",
		...section("Validation expectations", VALIDATION_HINTS),
		"",
		...section("Required evidence", EVIDENCE_BY_TIER[tier]),
		"",
		"Required return format:",
		"## Summary",
		"## Files Changed",
		"## Commands Run",
		"## Validation Result",
		"## Review Findings / Fixes Applied",
		"## Mental model update",
		"- What changed architecturally:",
		"- What future contributors should know:",
		"- Cognitive debt introduced or reduced:",
		"## Residual Risks",
		"## Verdict",
		"Ready/Not ready:",
	].filter((line): line is string => typeof line === "string");

	return { decision, prompt: prompt.join("\n") };
}

export function formatHandoff(handoff: DelegationHandoff): string {
	return ["```text", handoff.prompt, "```"].join("\n");
}
